spring:
  application:
    name: smart-dispatch-backend
  config:
    import: optional:file:.env[.properties]

  datasource:
    # Production Database (Injected by Render Environment Variables)
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smatchdispatch}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:123456789}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    # Production Cache
    host: ${REDIS_HOST:localhost}
    port: 6379
    ssl: ${REDIS_SSL:false}
    password: ${REDIS_PASSWORD:}

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    properties:
      sasl:
        mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
        jaas:
          config: ${KAFKA_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";}
      security:
        protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

  jwt:
    secret: ${JWT_SECRET:dfgrthfsfwet34dsfbfhfhwrt54tfds45ddsgdfg5yt45dgdgdeqrgdfhgjsewrwtreyrtutndfdsfsdfet45t4dgdfg4w5t45yrtgdset455ydfgdfgwrw45}
    expiration: 86400000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:sharma.princekumar0611@gmail.com}
    password: ${MAIL_PASSWORD:yevfjswycnzhenbh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] - %msg%n"

payment:
  stripe:
    public-key: ${STRIPE_PUBLIC_KEY}
    secret-key: ${STRIPE_SECRET_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  payu:
    key: ${PAYU_KEY}
    salt: ${PAYU_SALT}
  razorpay:
    key-id: ${RAZORPAY_KEY_ID}
    key-secret: ${RAZORPAY_KEY_SECRET}
    webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
  paystack:
    public-key: ${PAYSTACK_PUBLIC_KEY:mock_paystack_public_key}
    secret-key: ${PAYSTACK_SECRET_KEY:mock_paystack_secret_key}
  cashfree:
    app-id: mock_cashfree_app_id_test
    secret-key: mock_cashfree_secret_key_test

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      stripe:
        baseConfig: default
      razorpay:
        baseConfig: default
      paystack:
        baseConfig: default
      cashfree:
        baseConfig: default
