--
-- PostgreSQL database dump
--

\restrict LBINeok9fniPlocleSzDFSGo43KwlKuEBkJjC1pV6kt859AzNeRynycQprmm7qV

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: admin
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255),
    created_at timestamp(6) without time zone,
    entity_id bigint,
    entity_type character varying(255),
    ip_address character varying(255),
    new_value character varying(255),
    performed_by character varying(255),
    previous_value character varying(255)
);


ALTER TABLE public.audit_logs OWNER TO admin;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    active boolean,
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    discount_type character varying(255),
    discount_value double precision,
    max_discount double precision,
    max_usage integer,
    min_order_amount double precision,
    used_count integer,
    valid_from timestamp(6) without time zone,
    valid_until timestamp(6) without time zone
);


ALTER TABLE public.coupons OWNER TO admin;

--
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_documents; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.driver_documents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    document_number character varying(255) NOT NULL,
    document_type character varying(255) NOT NULL,
    document_url character varying(255),
    expiry_date date,
    rejection_reason character varying(255),
    updated_at timestamp(6) without time zone,
    verification_status character varying(255),
    verified_at timestamp(6) without time zone,
    driver_id bigint NOT NULL,
    CONSTRAINT driver_documents_document_type_check CHECK (((document_type)::text = ANY ((ARRAY['DRIVING_LICENSE'::character varying, 'VEHICLE_RC'::character varying, 'INSURANCE'::character varying, 'PAN_CARD'::character varying, 'AADHAAR_CARD'::character varying, 'VEHICLE_PERMIT'::character varying])::text[]))),
    CONSTRAINT driver_documents_verification_status_check CHECK (((verification_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.driver_documents OWNER TO admin;

--
-- Name: driver_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.driver_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_skill_tags; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.driver_skill_tags (
    driver_id bigint NOT NULL,
    skill_tag character varying(255),
    CONSTRAINT driver_skill_tags_skill_tag_check CHECK (((skill_tag)::text = ANY ((ARRAY['FRAGILE_HANDLING'::character varying, 'COLD_CHAIN'::character varying, 'HEAVY_LOAD'::character varying, 'EXPRESS_DELIVERY'::character varying, 'HAZARDOUS_MATERIAL'::character varying, 'FURNITURE'::character varying, 'FOOD_DELIVERY'::character varying, 'MEDICAL_SUPPLY'::character varying])::text[])))
);


ALTER TABLE public.driver_skill_tags OWNER TO admin;

--
-- Name: drivers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.drivers (
    id bigint NOT NULL,
    acceptance_rate double precision,
    active boolean,
    active_order_count integer,
    address character varying(500),
    city character varying(255),
    completion_rate double precision,
    created_at timestamp(6) without time zone,
    current_latitude double precision,
    current_longitude double precision,
    date_of_birth date,
    emergency_contact_name character varying(255),
    emergency_contact_phone character varying(255),
    last_active_at timestamp(6) without time zone,
    license_expiry date,
    license_number character varying(255),
    location_updated_at timestamp(6) without time zone,
    max_concurrent_orders integer,
    on_time_rate double precision,
    onboarded_at timestamp(6) without time zone,
    performance_score double precision,
    pincode character varying(255),
    preferred_zone character varying(255),
    profile_picture_url character varying(255),
    rating double precision,
    rejection_reason character varying(255),
    service_radius_km double precision,
    state character varying(255),
    status character varying(255) NOT NULL,
    tier character varying(255),
    total_deliveries integer,
    total_earnings double precision,
    total_ratings integer,
    total_trips integer,
    updated_at timestamp(6) without time zone,
    vehicle_capacity_kg double precision,
    vehicle_color character varying(255),
    vehicle_model character varying(255),
    vehicle_number character varying(255) NOT NULL,
    vehicle_type character varying(255) NOT NULL,
    vehicle_year integer,
    verification_status character varying(255),
    wallet_balance double precision,
    user_id bigint NOT NULL,
    CONSTRAINT drivers_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BUSY'::character varying, 'OFFLINE'::character varying, 'ON_BREAK'::character varying, 'SUSPENDED'::character varying])::text[]))),
    CONSTRAINT drivers_tier_check CHECK (((tier)::text = ANY ((ARRAY['BRONZE'::character varying, 'SILVER'::character varying, 'GOLD'::character varying, 'PLATINUM'::character varying])::text[]))),
    CONSTRAINT drivers_vehicle_type_check CHECK (((vehicle_type)::text = ANY ((ARRAY['BIKE'::character varying, 'CAR'::character varying, 'VAN'::character varying, 'TRUCK'::character varying, 'TEMPO'::character varying, 'AUTO_RICKSHAW'::character varying])::text[]))),
    CONSTRAINT drivers_verification_status_check CHECK (((verification_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.drivers OWNER TO admin;

--
-- Name: drivers_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drivers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    action_url character varying(255),
    created_at timestamp(6) without time zone,
    message character varying(2000),
    read boolean,
    title character varying(255),
    type character varying(255),
    user_id bigint,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['EMAIL'::character varying, 'SMS'::character varying, 'PUSH'::character varying, 'IN_APP'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO admin;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_timeline; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.order_timeline (
    id bigint NOT NULL,
    description character varying(255),
    status character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    updated_by character varying(255),
    order_id bigint NOT NULL,
    CONSTRAINT order_timeline_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'ASSIGNED'::character varying, 'PICKED_UP'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.order_timeline OWNER TO admin;

--
-- Name: order_timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.order_timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    assigned_at timestamp(6) without time zone,
    cancellation_reason character varying(255),
    cancelled_at timestamp(6) without time zone,
    cancelled_by character varying(255),
    created_at timestamp(6) without time zone,
    customer_feedback character varying(255),
    customer_notes character varying(1000),
    customer_rating double precision,
    delivered_at timestamp(6) without time zone,
    delivery_fee double precision,
    delivery_otp character varying(255),
    distance_km double precision,
    drop_address character varying(255) NOT NULL,
    drop_contact_name character varying(255),
    drop_contact_phone character varying(255),
    drop_latitude double precision,
    drop_longitude double precision,
    estimated_delivery_at timestamp(6) without time zone,
    in_transit_at timestamp(6) without time zone,
    package_description character varying(255),
    package_type character varying(255),
    package_weight_kg double precision,
    picked_up_at timestamp(6) without time zone,
    pickup_address character varying(255) NOT NULL,
    pickup_contact_name character varying(255),
    pickup_contact_phone character varying(255),
    pickup_latitude double precision,
    pickup_longitude double precision,
    pickup_otp character varying(255),
    priority character varying(255),
    status character varying(255) NOT NULL,
    tracking_number character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    customer_id bigint NOT NULL,
    driver_id bigint,
    assignment_attempts integer,
    coupon_code character varying(255),
    discount_amount double precision,
    is_scheduled boolean,
    last_assignment_attempt_at timestamp(6) without time zone,
    max_assignment_attempts integer,
    scheduled_at timestamp(6) without time zone,
    surge_multiplier double precision,
    CONSTRAINT orders_package_type_check CHECK (((package_type)::text = ANY ((ARRAY['DOCUMENT'::character varying, 'SMALL_PARCEL'::character varying, 'MEDIUM_PARCEL'::character varying, 'LARGE_PARCEL'::character varying, 'FRAGILE'::character varying, 'FOOD'::character varying, 'MEDICAL'::character varying, 'ELECTRONICS'::character varying, 'FURNITURE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT orders_priority_check CHECK (((priority)::text = ANY ((ARRAY['STANDARD'::character varying, 'EXPRESS'::character varying, 'URGENT'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'ASSIGNED'::character varying, 'PICKED_UP'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO admin;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO admin;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_provider_metrics; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.payment_provider_metrics (
    id bigint NOT NULL,
    avg_latency_ms double precision,
    failure_count bigint,
    last_failure_at timestamp(6) without time zone,
    provider character varying(255) NOT NULL,
    success_count bigint,
    success_rate double precision,
    total_requests bigint,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.payment_provider_metrics OWNER TO admin;

--
-- Name: payment_provider_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.payment_provider_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_provider_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount double precision,
    created_at timestamp(6) without time zone,
    currency character varying(255),
    customer_id bigint,
    failure_reason character varying(255),
    gateway_order_id character varying(255),
    gateway_payment_id character varying(255),
    idempotency_key character varying(255),
    max_retries integer,
    method character varying(255),
    order_id bigint,
    paid_at timestamp(6) without time zone,
    provider_transaction_id character varying(255),
    refunded_at timestamp(6) without time zone,
    retry_count integer,
    status character varying(255),
    transaction_id character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['WALLET'::character varying, 'RAZORPAY'::character varying, 'STRIPE'::character varying, 'PAYPAL'::character varying, 'CASHFREE'::character varying, 'UPI'::character varying, 'CARD'::character varying, 'NET_BANKING'::character varying, 'CASH_ON_DELIVERY'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'INITIATED'::character varying, 'PROCESSING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO admin;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone,
    revoked boolean,
    token character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.refresh_tokens OWNER TO admin;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refunds; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.refunds (
    id bigint NOT NULL,
    amount double precision,
    completed_at timestamp(6) without time zone,
    gateway_refund_id character varying(255),
    initiated_at timestamp(6) without time zone,
    order_id bigint,
    payment_id bigint,
    reason character varying(255),
    status character varying(255)
);


ALTER TABLE public.refunds OWNER TO admin;

--
-- Name: refunds_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.refunds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refunds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255),
    CONSTRAINT roles_name_check CHECK (((name)::text = ANY ((ARRAY['ADMIN'::character varying, 'DISPATCHER'::character varying, 'DRIVER'::character varying, 'CUSTOMER'::character varying])::text[])))
);


ALTER TABLE public.roles OWNER TO admin;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_addresses; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.saved_addresses (
    id bigint NOT NULL,
    contact_name character varying(255),
    contact_phone character varying(255),
    created_at timestamp(6) without time zone,
    full_address character varying(255) NOT NULL,
    is_default boolean,
    label character varying(255) NOT NULL,
    landmark character varying(255),
    latitude double precision,
    longitude double precision,
    user_id bigint
);


ALTER TABLE public.saved_addresses OWNER TO admin;

--
-- Name: saved_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.saved_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_zones; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.service_zones (
    id bigint NOT NULL,
    active boolean,
    center_latitude double precision,
    center_longitude double precision,
    city character varying(255),
    name character varying(255) NOT NULL,
    radius_km double precision,
    zone_multiplier double precision
);


ALTER TABLE public.service_zones OWNER TO admin;

--
-- Name: service_zones_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.service_zones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone_no character varying(255),
    updated_at timestamp(6) without time zone,
    role_id bigint,
    city character varying(255),
    date_of_birth character varying(255),
    deactivation_reason character varying(255),
    default_address character varying(255),
    default_latitude double precision,
    default_longitude double precision,
    gender character varying(255),
    last_login_at timestamp(6) without time zone,
    last_login_device character varying(255),
    last_login_ip character varying(255),
    loyalty_points integer,
    notifications_enabled boolean,
    pincode character varying(255),
    preferred_language character varying(255),
    profile_picture_url character varying(255),
    referral_code character varying(255),
    referral_count integer,
    referred_by character varying(255),
    sms_enabled boolean,
    state character varying(255),
    total_orders integer,
    total_spent integer,
    wallet_balance double precision,
    active boolean DEFAULT true NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    phone_verified boolean DEFAULT false NOT NULL
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_ledger; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.wallet_ledger (
    id bigint NOT NULL,
    amount double precision,
    balance_after double precision,
    created_at timestamp(6) without time zone,
    description character varying(255),
    reference_id character varying(255),
    source character varying(255),
    type character varying(255),
    user_id bigint,
    wallet_id bigint
);


ALTER TABLE public.wallet_ledger OWNER TO admin;

--
-- Name: wallet_ledger_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.wallet_ledger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    balance double precision,
    created_at timestamp(6) without time zone,
    frozen boolean,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.wallets OWNER TO admin;

--
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- Name: driver_documents driver_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.driver_documents
    ADD CONSTRAINT driver_documents_pkey PRIMARY KEY (id);


--
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: order_timeline order_timeline_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_timeline
    ADD CONSTRAINT order_timeline_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: payment_provider_metrics payment_provider_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.payment_provider_metrics
    ADD CONSTRAINT payment_provider_metrics_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refunds refunds_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT refunds_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: saved_addresses saved_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.saved_addresses
    ADD CONSTRAINT saved_addresses_pkey PRIMARY KEY (id);


--
-- Name: service_zones service_zones_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.service_zones
    ADD CONSTRAINT service_zones_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: refresh_tokens uk7tdcd6ab5wsgoudnvj7xf1b7l; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk7tdcd6ab5wsgoudnvj7xf1b7l UNIQUE (user_id);


--
-- Name: service_zones uk8c0orle6cmpmryy4mqe1qwse4; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.service_zones
    ADD CONSTRAINT uk8c0orle6cmpmryy4mqe1qwse4 UNIQUE (name);


--
-- Name: users ukdb3w2sgtsy1kf0qitc77h0bpa; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdb3w2sgtsy1kf0qitc77h0bpa UNIQUE (referral_code);


--
-- Name: coupons ukeplt0kkm9yf2of2lnx6c1oy9b; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukeplt0kkm9yf2of2lnx6c1oy9b UNIQUE (code);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: payments ukj4pdqn1207fuhx2gybp1ue799; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT ukj4pdqn1207fuhx2gybp1ue799 UNIQUE (idempotency_key);


--
-- Name: payment_provider_metrics ukkveopy9y7rhiru3u91ol5saxa; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.payment_provider_metrics
    ADD CONSTRAINT ukkveopy9y7rhiru3u91ol5saxa UNIQUE (provider);


--
-- Name: payments uklryndveuwa4k5qthti0pkmtlx; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uklryndveuwa4k5qthti0pkmtlx UNIQUE (transaction_id);


--
-- Name: orders uknew938pg97mqegt6j0irfoimc; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uknew938pg97mqegt6j0irfoimc UNIQUE (tracking_number);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: drivers ukojm6yjeacqc5cthc73k5twsnj; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT ukojm6yjeacqc5cthc73k5twsnj UNIQUE (user_id);


--
-- Name: wallets uksswfdl9fq40xlkove1y5kc7kv; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT uksswfdl9fq40xlkove1y5kc7kv UNIQUE (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wallet_ledger wallet_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallet_ledger
    ADD CONSTRAINT wallet_ledger_pkey PRIMARY KEY (id);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: driver_documents fk4cqh5sfs29eeky0q37t2x78vq; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.driver_documents
    ADD CONSTRAINT fk4cqh5sfs29eeky0q37t2x78vq FOREIGN KEY (driver_id) REFERENCES public.drivers(id);


--
-- Name: drivers fkfscpnjt46gco44xh86l99rxh7; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT fkfscpnjt46gco44xh86l99rxh7 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: order_timeline fkku427emlhtsh9ktlgk5duuyv9; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_timeline
    ADD CONSTRAINT fkku427emlhtsh9ktlgk5duuyv9 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: driver_skill_tags fkl9vbliyx5nvu06yiehoqddswm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.driver_skill_tags
    ADD CONSTRAINT fkl9vbliyx5nvu06yiehoqddswm FOREIGN KEY (driver_id) REFERENCES public.drivers(id);


--
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: orders fkqohd0dujmkcb12rcjy4b1fj4u; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkqohd0dujmkcb12rcjy4b1fj4u FOREIGN KEY (driver_id) REFERENCES public.drivers(id);


--
-- Name: orders fksjfs85qf6vmcurlx43cnc16gy; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fksjfs85qf6vmcurlx43cnc16gy FOREIGN KEY (customer_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict LBINeok9fniPlocleSzDFSGo43KwlKuEBkJjC1pV6kt859AzNeRynycQprmm7qV

